### ISSUE TITLE
[Question] Does the project support Windows?

### ISSUE THREAD

**Issue by tan-wei** [crayzeewulf/libserial#140]
I think MSVC is not support, `Cygwin` or `MinGW` is fine if supported. Thanks!

**Comment by crayzeewulf** [comment]
@tan-wei I am sorry but this project does not support Windows. You can try using other libraries such as  [Qt Serial Port](https://doc.qt.io/qt-5/qtserialport-index.html) or [Boost.Asio](https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/serial_port.html).

**Comment by tan-wei** [comment]
Thanks for your summary.  Quite helpful for me.
Hope you have a good day.
