### ISSUE TITLE
Question about timeout capability of  serialstream class

### ISSUE THREAD

**Issue by chaz765** [crayzeewulf/libserial#154]
Hi, 
Looked at all the code samples and really liked the library, would like to see a simple example with serialstream class which uses timeout. 
-cn

**Comment by crayzeewulf** [comment]
@chaz765 You can find some examples in the unit tests under the tests folder. I am traveling for a couple of weeks with minimal internet access. If the code of the unit tests does not help, please let me know and I will get you something specific for your need.

**Comment by chaz765** [comment]
I ended up using the SerialPort class instead and it seems to be working fine.

**Comment by crayzeewulf** [comment]
Glad to hear that `SerialPort` class worked out for you. Thanks for the update!
