### ISSUE TITLE
 boost/test/unit_test.hpp: No such file or directory

### ISSUE THREAD

**Issue by MareFonseca** [crayzeewulf/libserial#158]
I have the error  boost/test/unit_test.hpp: No such file or directory when I do make

**Comment by crayzeewulf** [comment]
Hi @MareFonseca:

You will have to install the Boost Unit Test library and headers. See [this](https://github.com/crayzeewulf/libserial#developers) section, for some instructions. In particular, if you are using Debian/Ubuntu then you will need to install `libboost-test-dev` package.

**Comment by MareFonseca** [comment]
This works! thanks
