### ISSUE TITLE
errno could be 0 when exception is thrown

### ISSUE THREAD

**Issue by liubing** [crayzeewulf/libserial#161]
Hi,

In SerialPort.cpp, function SerialPort::Implementation::SetVMin(const short vmin), line 1641:
```
        if (vmin < 0 || vmin > 255)
        {
            throw std::invalid_argument(std::strerror(errno)) ;
        }

```
When the exception is thrown, errno chould be 0.
I think it could be better to replace strerror() with a custom message.

**Comment by crayzeewulf** [comment]
Nice catch. You are right. This needs fixing. Thanks for reporting this issue.
