### ISSUE TITLE
error in make command for serial communication in ubuntu

### ISSUE THREAD

**Issue by parijohn** [crayzeewulf/libserial#57]
I am running this program in ubuntu 14.04.3 and it gives error in the very first command "make -f Makefile.dist"
*************
pari7@john-pari:~/project/libserial-master$ make -f Makefile.dist
mkdir -pv m4
autoreconf -i --force  --verbose
make: autoreconf: Command not found
make: *** [all] Error 127
*************
I need urgent help please..

**Comment by crayzeewulf** [comment]
You need to install `autoconf` first. Use the command:

    sudo apt-get install autoconf

If any other tool (such as libtool or automake) is missing, please install it from Ubuntu's package repository and building libserial again.
