### ISSUE TITLE
SerialStream::operator=(const LibSerial::SerialStream&)’ is private

### ISSUE THREAD

**Issue by bidasknakayama** [crayzeewulf/libserial#60]
Hello

To copy "SerialStream" instance to array, 
it is not possible with this error.

    SerialStream.h:260:27: error:
     ‘LibSerial::SerialStream& LibSerial::SerialStream::operator=
    (const LibSerial::SerialStream&)’ is private

if I comment out 2 line and re-build, Is it be problem ?

    SerialStream( const SerialStream& ) ;
    SerialStream& operator=( const SerialStream& ) ;

I want to copy instance to array to use later..
Please advice me.

Kazu

**Comment by crayzeewulf** [comment]
Kazu:

Instances of SerialStream class cannot be copied in the current design. If you need to put them in an arrays please consider using [std::unique_ptr](http://en.cppreference.com/w/cpp/memory/unique_ptr) or  [std::shared_ptr](http://en.cppreference.com/w/cpp/memory/shared_ptr). 
--
CrayzeeWulf
