### ISSUE TITLE
Failure to compile on Ubuntu ARM

### ISSUE THREAD

**Issue by daltonfury42** [crayzeewulf/libserial#63]
Hey,

I am getting this error when I do a 'make':

> make  all-recursive
> make[1]: Entering directory `/home/ubuntu/moos-ivp/libserial'
> Making all in src
> make[2]: Entering directory`/home/ubuntu/moos-ivp/libserial/src'
> /bin/bash ../libtool  --tag=CXX   --mode=link g++ -Weffc++ -g -O2   -o unit_tests unit_tests.o libserial.la -lboost_unit_test_framework 
> libtool: link: g++ -Weffc++ -g -O2 -o .libs/unit_tests unit_tests.o  ./.libs/libserial.so -lboost_unit_test_framework
> /usr/bin/ld: cannot find -lboost_unit_test_framework
> collect2: error: ld returned 1 exit status
> make[2]: **\* [unit_tests] Error 1
> make[2]: Leaving directory `/home/ubuntu/moos-ivp/libserial/src'
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory`/home/ubuntu/moos-ivp/libserial'
> make: **\* [all] Error 2

**Comment by crayzeewulf** [comment]
Hi:

You need to install the Boost libraries on your distribution in order to build `libserial`. These libraries ought to be available via the Ubuntu package manager. Please let me know if you need help installing Boost.
--
CrayzeeWulf
