### ISSUE TITLE
CMake Include Target property

### ISSUE THREAD

**Issue by Klirxel** [crayzeewulf/libserial#80]
Hello libserialTeam

I cant integrate libserial in my CMake project without workaround.
Include files are not added to the public interface for LibSerial.

Please add to src/CMakeLists.txt

`target_include_directories (LibSerial PUBLIC ${CMAKE_CURRENT_LIST_DIR})
`

Besides than you should be able to delete 
`INCLUDE_DIRECTORIES(
  src
)`
in your main CMakeLists.txt.

**Comment by mcsauder** [comment]
Hi Klirxel,

Thanks for posting the issue.  I've implemented your solution and pushed the commit into the (currently active) PR #79 .

Thanks for the patch hint!

-Mark

**Comment by mcsauder** [comment]
Hi Klirxel,

I think everything is fixed up now in both the development branch and the master branch so I'll close this issue.  Please let us know if you spot anything else that can be improved!

-Mark
