### ISSUE TITLE
The examples/ does not contains SerialPort  Read+Timeout example

### ISSUE THREAD

**Issue by wade-fs** [crayzeewulf/libserial#94]
The examples/ does not contains SerialPort  Read+Timeout example
[LibSerial-Examples.zip](https://github.com/crayzeewulf/libserial/files/1520390/LibSerial-Examples.zip)

**Comment by mcsauder** [comment]
Hi Wade,

Could you let me know if PR #95 does a better job of showing how to handle ReadTimeout exceptions: and if so we can add that commit?

Thanks again for your help making LibSerial better!

-Mark

**Comment by mcsauder** [comment]
Hi @wade-fs ,

I've added an example to the serial_port_read.cpp example file in PR #97 that matches your use case of unknown number of bytes being read during a given timeout period.  Let me know if this is what you had in mind!

Thanks again for submitting the issue!

-Mark

**Comment by mcsauder** [comment]
Hi @wade-fs ,

Fixed in PR #97!

-Mark
